### ISSUE TITLE
401 Le jeton d'accès n'est pas valide

### ISSUE THREAD

**Issue by vincentux** [YunoHost-Apps/mastodon_ynh#6] opened 2017-04-19 18:07 UTC
L'installation c'est très bien dérouler, bravo pour le travail ;)
Seulement quand je me connecte j'ai ce message en bas à gauche.

![selection_068](https://cloud.githubusercontent.com/assets/11737560/25194722/a088a880-253b-11e7-9735-6696a84a9f6a.jpg)

**Comment by GuillermoAnkh** [comment] 2019-08-11 15:21
Bonjour, j'ai le même problème et je ne trouve pas de solution actuellement.

**Comment by alexAubin** [comment] 2019-08-17 13:02
Following some investigation with @yalh76, the cause of the issue is described here : https://github.com/YunoHost/issues/issues/1420

From the app's side : 
- The issue apparently only appears if you install a 'private' instance (is_public set to False). Installing in public mode should fix the issue if that's okay for you
- There is a dirty and unsecure workaround that we discussed with @yalh76 about bypassing the SSOwat mechanism for some URI
- The real fix should happen in the core (implement a new setting in our SSO mechanism to not mess with Authorization header)
- The *real true ideal fix* would be that this app (and others) support Basic HTTP auth ... but I'm not really expert about this stuff and don't know if that's even possible or relevant ... but that sounds necessary if we ever want to have an SSO integration for these

**Comment by Silverscott** [comment] 2019-11-28 09:16
Hello all 

have the same bug, is there some new tricks to solve this problem ?

Thx

**Comment by yalh76** [comment] 2019-12-23 20:41
> 
> 
> Hello all
> 
> have the same bug, is there some new tricks to solve this problem ?
> 
> Thx

For now, the only workaround is to install in public and to not be logged into Yunohost when accessing Mastodon....

**Comment by erdmaennchen1** [comment] 2020-03-01 02:55
I am experiencing the same issue. 
It's weird because on a different install, a few days ago, I wasn't experiencing this issue.

**Comment by ImaCrea** [comment] 2020-04-06 10:01
Hi there, I keep seeing this issue also. I thought I needed to restart the instance to fix it, now I understood I need to be logged out from yh it's much easier :) Thank for the tip meanwhile we find a fix. cheers

**Comment by yalh76** [comment] 2021-03-06 17:28
Fixed by #260

**Closed by yalh76** 2021-03-06 17:28 UTC
Labels: bug

**Comment by 8cH9azbsFifZ** [comment] 2022-06-16 22:46
> Following some investigation with @yalh76, the cause of the issue is described here : [YunoHost/issues#1420](https://github.com/YunoHost/issues/issues/1420)
> 
> From the app's side :
> 
> * The issue apparently only appears if you install a 'private' instance (is_public set to False). Installing in public mode should fix the issue if that's okay for you
> * There is a dirty and unsecure workaround that we discussed with @yalh76 about bypassing the SSOwat mechanism for some URI
> * The real fix should happen in the core (implement a new setting in our SSO mechanism to not mess with Authorization header)
> * The _real true ideal fix_ would be that this app (and others) support Basic HTTP auth ... but I'm not really expert about this stuff and don't know if that's even possible or relevant ... but that sounds necessary if we ever want to have an SSO integration for these

The last point you mentioned is the solution. So we have to wait for an implementation of this basic feature :)

**Comment by yalh76** [comment] 2022-06-17 06:37
it's already implmented

**Comment by erikmakela** [comment] 2026-02-16 00:57
@alexAubin I would like to raise to this that this issue seems to be reproducible to some degree on any instance of mastodon that is packaged for yunohost. I have tried to locate a resolution to this issue and it seems to have gone stale for running any kind of federation mastodon federation. However, lemmy / fedipie seem to be working fine.
